# Generated by Django 6.0.2 on 2026-02-17 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_libro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editorial',
            old_name='fecha_funcadion',
            new_name='fecha_fundacion',
        ),
    ]
