# Generated by Django 6.0.2 on 2026-02-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_fecha_funcadion_editorial_fecha_fundacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='idioma',
            field=models.CharField(choices=[('ES', 'Español'), ('EN', 'Inglés')], default='ES', max_length=2),
        ),
    ]
