# Generated by Django 6.0.2 on 2026-03-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_autor_premios_alter_autor_sitio_web_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
