# Generated by Django 6.0.2 on 2026-03-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_editorial_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='fecha_nacimiento',
            field=models.DateField(error_messages={'invalid': '¡Oye! la fecha de nacimiento debe ir en el formato DD/MM/AAAA.', 'required': '¡Oye! la fecha de nacimiento es un campo obligatorio.'}),
        ),
    ]
