# Generated by Django 6.0.2 on 2026-03-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_autor_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
