# Generated by Django 6.0.2 on 2026-03-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_autor_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='apellido_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='apellido_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='nombre_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='nombre_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='descripcion_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='descripcion_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='titulo_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='titulo_es',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
