# Generated by Django 6.0.2 on 2026-03-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_autor_apellido_en_autor_apellido_es_autor_nombre_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autores',
            field=models.ManyToManyField(to='books.autor'),
        ),
    ]
