# Generated by Django 4.2.29 on 2026-03-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_libro_autores'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='is_out_of_stock',
            field=models.BooleanField(default=False, verbose_name='Está fuera de stock'),
        ),
    ]
