# Generated by Django 4.2.29 on 2026-03-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_editorial_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='level',
            field=models.CharField(choices=[('1', 'Nivel 1'), ('2', 'Nivel 2'), ('3', 'Nivel 3')], default='1', max_length=2, verbose_name='Nivel'),
        ),
    ]
