# Generated by Django 5.2.12 on 2026-03-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_alter_editorial_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial',
            name='nombre_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='editorial',
            name='nombre_es',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
