# Generated by Django 5.2.12 on 2026-03-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_editorial_nombre_en_editorial_nombre_es'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='biografia_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='biografia_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='nacionalidad_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='nacionalidad_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editorial',
            name='ciudad_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editorial',
            name='ciudad_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editorial',
            name='pais_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editorial',
            name='pais_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='genero_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='genero_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
